version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    command:
      - npx
      - nodos
      - server
      - -h
      - 0.0.0.0
    volumes:
      - .:/app
    ports:
      - '8080:8080'

  caddy:
    image: caddy:2-alpine
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'
    depends_on:
      - app
