version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    command:
      - make
      - server
    volumes:
      - ./app:/app
    ports:
      - '8080:8080'
    env_file: .env

  db:
    env_file: .env

  caddy:
    image: caddy:2-alpine
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './services/caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './services/caddy/data/:/data'
      - './services/caddy/config/:/config'
    depends_on:
      - app
    env_file: .env
